name: CI and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run test:cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t autostrada:latest .

      - name: Tag Docker image
        run: |
          docker tag autostrada:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/autostrada:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/autostrada:latest

      - name: Deploy to on-premises host
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            sh -c '
            aws ecr get-login-password --region ${{ vars.AWS_REGION }} | \
            docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/autostrada:latest

            docker stop autostrada || true
            docker rm autostrada || true

            LOG_STREAM_UUID=$(uuidgen)

            docker run -d --name autostrada \
            --memory=256m \
            --memory-swap=256m \
            -p ${{ vars.HTTP_PORT }}:${{ vars.HTTP_PORT }} \
            -p ${{ vars.GRPC_PORT }}:${{ vars.GRPC_PORT }} \
            -e AWS_REGION=${{ vars.AWS_REGION }} \
            -e AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} \
            -e COGNITO_USER_POOL_ID=${{ secrets.COGNITO_USER_POOL_ID }} \
            -e DB_CREDENTIALS="${{ secrets.DB_CREDENTIALS }}" \
            -e DB_DATABASE="${{ secrets.DB_DATABASE }}" \
            -e SERVICE_FQDN="${{ secrets.SERVICE_FQDN }}" \
            -e TALKBACK_FQDN="${{ secrets.TALKBACK_FQDN }}" \
            -e POMPEII_GRPC_URL="${{ secrets.POMPEII_GRPC_URL }}" \
            -e POMPEII_KEY="${{ secrets.POMPEII_KEY }}" \
            -e HTTP_PORT="${{ vars.HTTP_PORT }}" \
            -e GRPC_PORT="${{ vars.GRPC_PORT }}" \
            -e ASSETS_BUCKET_NAME="${{ secrets.ASSETS_BUCKET_NAME }}" \
            -e N8N_API_KEY="${{ secrets.N8N_API_KEY }}" \
            -e N8N_WEBHOOK="${{ secrets.N8N_WEBHOOK }}" \
            -e CONTAINERIZED=true \
            --restart=always \
            --log-driver=awslogs \
            --log-opt awslogs-region=${{ vars.AWS_REGION }} \
            --log-opt awslogs-group=${{ vars.LOGS_GROUP }} \
            --log-opt awslogs-stream="$LOG_STREAM_UUID" \
            -v ~/.aws:/root/.aws:ro \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/autostrada:latest
            '